import json
import random
from all_global_vars import all_global_vars
from typing import Any, Dict
from open_ai_api import call_ai


ITEM_TYPES = {"weapons", "armor", "accessory", "consumable", "junk"}
RARITIES = {"Common", "Uncommon", "Rare", "Epic", "Legendary"}

ITEM_VALUES = {
    "Common": (1, 8),
    "Uncommon": (10, 30),
    "Rare": (40, 120),
    "Epic": (150, 400),
    "Legendary": (500, 1200),
}

ITEM_SCHEMA_EXAMPLE = [
    {
        "name": "rusty dagger",
        "type": "weapon",
        "rarity": "Common",
        "value": 1,
        "desc": "A pitted blade with a worn leather grip.",
        "damage": 1
    }
]

ITEM_PROMPT = (
    "You are an item generator for a text-adventure RPG.\n"
    "Given a THEME, ROOM DESCRIPTION, and ROOM TYPE, generate between 1 and 3 items "
    "that would be found in the given location.\n"
    "Produce a compact JSON object following the exact SCHEMA.\n"
    "Rules:\n"
    "- Return ONLY minified JSON (no markdown, no comments)\n"
    "- Select one rarity: Common|Uncommon|Rare|Epic|Legendary\n"
    "- Include a 'damage' value (1-20) ONLY for items whose type is 'weapons'\n"
    "- Include an 'armor' value (1-10) ONLY for items whose type is 'armor'\n"
    "- Skew more towards creating Common and Uncommon rarities\n"
)


# AI Item Generation
def _build_item_prompt(theme, room_description, room_identity):
    """
    Prompt setup, similar to room generation prompt, for AI to generate items for a given room.
    """
    return (
        ITEM_PROMPT
        + "\nSCHEMA=" + json.dumps(ITEM_SCHEMA_EXAMPLE)
        + "\nTHEME=" + theme
        + "\nROOM TYPE=" + (room_identity or "general")
        + "\nROOM DESCRIPTION=" + (room_description or "a dimly lit room")
        + "\nJSON:"
    )


def _validate_ai_items(item):
    """
    Validate items generated by AI to ensure they have all the required values before adding them to the room.
    """
    if not isinstance(item, dict):
        return None

    name = item.get("name")
    if not name or not isinstance(name,str):
        return None

    item_type = item.get("type", "tool")
    if item_type not in ITEM_TYPES:
        item_type = "tool"

    rarity = item.get("rarity", "Common")
    if rarity not in RARITIES:
        rarity = "Common"

    low, high = ITEM_VALUES.get(rarity, (1,8))
    try:
        value = int(item.get("value", random.randint(low,high)))
        value = max(low, min(high, value))
    except (TypeError, ValueError):
        value = random.randint(low, high)

    desc = item.get("desc")
    if not desc or not isinstance(desc, str):
        desc = "A common item."

    valid_item = {
        "name": name.strip(),
        "type": item_type,
        "rarity": rarity,
        "value": value,
        "desc": desc.strip()
    }

    if item_type == "weapon":
        try:
            damage = int(item.get("damage", random.randint(1,5)))
            valid_item["damage"] = max(1, min(20, damage))
        except (TypeError, ValueError):
            valid_item["damage"] = random.randint(1,5)

    elif item_type == "armor":
        try:
            armor = int(item.get("armor", random.randint(1,4)))
            valid_item["armor"] = max(1, min(15, armor))
        except (TypeError, ValueError):
            valid_item["armor"] = random.randint(1,4)

    return valid_item


def get_ai_items(theme: str, room_description: str, room_identity: str, random_seed):
    """
    Prompt GenAI to create 1-3 items to be placed into the given room.
    """
    prompt = _build_item_prompt(theme or "Unknown", room_description or "Unknown", room_identity or "Unknown")
    try:
        raw = call_ai(prompt)
        # Try to extract JSON
        raw = raw.strip()
        # If wrapped in code fences, remove them
        if raw.startswith("```") and raw.endswith("```"):
            raw = raw.strip("`\n")
        # Some models may prepend text; find first '{' and last '}'
        start = raw.find('[')
        end = raw.rfind(']')
        if start != -1 and end != -1:
            raw = raw[start:end + 1]
        response = json.loads(raw)

        # Validate that each item created is a valid item
        validated_items = []
        for item in response[:3]:
            valid = _validate_ai_items(item)
            if valid is not None:
                validated_items.append(valid)

        if not validated_items:
            raise ValueError("No items are valid")

        return validated_items

    except Exception:
        print("Error pulling AI items, resorting to default item generation")
        # Fallback default layout
        def_items = default_items(theme, random_seed)
        return def_items

def default_items(theme, seed_value):
    """
    Default fallback option for generating items in case the GenAI fails to properly create items.
    """
    random.seed(seed_value)

    if "cyber" in theme:
        base_items = [
            ("credits chip", "currency", "A small encoded chip worth a few credits."),
            ("data shard", "junk", "Encrypted storage crystal."),
            ("plasma cell", "junk", "Hums faintly with charge."),
            ("medkit", "junk", "Sterile wraps and coagulant foam."),
            ("neural jack", "junk", "A small cortex interface plug."),
            ("encrypted drive", "junk", "Locked storage device, data unknown."),
            ("stim patch", "junk", "Adhesive stimulant strip."),
            ("keycard", "junk", "A magnetic access card, lightly scratched."),
            ("synth fiber", "junk", "A coil of high-tensile synthetic cord."),
            ("micro drone", "junk", "A palm-sized recon drone, damaged."),
        ]
    elif "steam" in theme:
        base_items = [
            ("cog token", "junk", "A brass token stamped with a gear emblem."),
            ("gear fragment", "junk", "Jagged cog from a larger machine."),
            ("metal scrap", "junk", "Useful for patchwork repairs."),
            ("oil flask", "junk", "Stoppered flask of machine oil."),
            ("sealed vial", "junk", "Opaque fluid, cool to touch."),
            ("copper tube", "junk", "A short length of pressure-rated piping."),
            ("wrench", "junk", "A heavy iron spanner, well-worn."),
            ("pressure gauge", "junk", "Cracked glass dial, still functional."),
            ("brass compass", "junk", "Engraved compass with a spinning needle."),
            ("steam crystal", "junk", "A heat-resonant mineral shard."),
        ]
    else:  # Medieval
        base_items = [
            ("bronze coin", "currency", "Ancient coin, its face worn smooth."),
            ("rusty dagger", "weapon", "A pitted blade with a worn leather grip."),
            ("leather satchel", "junk", "A weathered satchel with a broken clasp."),
            ("torch", "junk", "Wrapped in pitch-soaked cloth."),
            ("old map", "junk", "Faded parchment with partial routes."),
            ("copper key", "junk", "Small key etched with runes."),
            ("rations", "junk", "Dry but filling travel food."),
            ("rope", "junk", "Coiled hemp rope, 30ft."),
            ("gemstone", "junk", "Uncut gem catching stray light."),
            ("ancient scroll", "junk", "Sealed with brittle wax."),
        ]

    rarity_table = [
        ("Common", 1.0),
        ("Uncommon", 0.4),
        ("Rare", 0.18),
        ("Epic", 0.08),
        ("Legendary", 0.02),
    ]

    def pick_rarity():
        r = random.random()
        acc = 0.0
        for name, prob in rarity_table:
            acc += prob
            if r <= acc:
                return name
        return "Common"

    def item_value(rarity):
        base = {
            "Common": (1, 8),
            "Uncommon": (10, 30),
            "Rare": (40, 120),
            "Epic": (150, 400),
            "Legendary": (500, 1200),
        }.get(rarity, (1, 8))
        return random.randint(*base)

    item_count = random.randint(2, 4)
    chosen = random.sample(base_items, item_count)
    items = []
    for name, item_type, desc in chosen:
        rarity = pick_rarity()
        items.append({
            "name": name,
            "type": item_type,
            "rarity": rarity,
            "value": item_value(rarity),
            "desc": desc,
        })

    return items

